### ISSUE TITLE
uYou+: You need to enable Wi-Fi sync to install AltStore

### ISSUE THREAD

**Issue by aaronliu0130** [LeafandJam/leaf-guides#1]
see https://faq.altstore.io/getting-started/how-to-install-altstore-macos and https://faq.altstore.io/getting-started/how-to-install-altstore-windows

TL;DR: Before the "Install AltStore to your phone" step, add a step of enabling Wi-Fi sync in iTunes on 10.14.4 and Windows and enabling "Show This iPad over Wi-Fi" in Finder on 10.15+

**Comment by aaronliu0130** [comment]
This still isn't completely completed, the macOS part still hasn't been fixed.

**Comment by LeafandJam** [comment]
Thanks @aaronliu0130 it should be fixed now :)

**Comment by aaronliu0130** [comment]
Looks good, thanks!
